name: Release

description: Release packages

inputs:
  github_token:
    description: GitHub token
    required: true
  npm_token:
    description: NPM token
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
   
    - name: Setup Git
      run: |
        git config user.name "GitHub Bot"
        git config user.email "gituser@example.com"
      shell: bash

    - name: Install dependencies
      run: pnpm install
      shell: bash

    - name: Version
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm_token }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: pnpm nx affected -t version --base=last-release
      shell: bash
      
    - name: Tag last-release
      run: |
        git tag -f last-release
        git push origin last-release --force
      shell: bash
