name: Release

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
   
    - name: Setup Git
      run: |
        git config user.name "GitHub Bot"
        git config user.email "gituser@example.com"

    - run: pnpm i --frozen-lockfile --prod

    - name: Version
      shell: bash
      run: pnpm nx affected --base=last-release --target=version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Tag last-release
      shell: bash
      run: |
        git tag -f last-release
        git push origin last-release --force
