name: Release

inputs:
  github_token:
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
   
    - name: Setup Git
      run: |
        git config user.name "GitHub Bot"
        git config user.email "gituser@example.com"
      shell: bash

    - name: Version
      run: pnpm nx affected --base=last-release --target=version
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}

    - name: Tag last-release
      run: |
        git tag -f last-release
        git push origin last-release --force
      shell: bash
